### ISSUE TITLE
boolean has problem.. how can i solve it?

### ISSUE THREAD

**Issue by ilileun** [zyjiao4728/POG-Demo#1]
Traceback (most recent call last):
  File "/home/libra/vscode_ji/pybullet/POG-Demo/pog_example/iros_2022_exp/exp2/main.py", line 31, in <module>
    g_start = Graph('exp2-init', file_dir='pog_example/iros_2022_exp/exp2/', file_name='init.json')
  File "/home/libra/vscode_ji/pybullet/POG-Demo/pog/graph/graph.py", line 68, in __init__
    temp_node = Wardrobe.from_saved(n)
  File "/home/libra/vscode_ji/pybullet/POG-Demo/pog/graph/shapes/complex_storage.py", line 74, in from_saved
    return cls(size=n['size'], transform=np.array(n['transform']))
  File "/home/libra/vscode_ji/pybullet/POG-Demo/pog/graph/shapes/wardrobe.py", line 22, in __init__
    super().__init__(shape_type, size, transform, storage_type, **kwargs)
  File "/home/libra/vscode_ji/pybullet/POG-Demo/pog/graph/shapes/complex_storage.py", line 59, in __init__
    outer_shape.difference(inner_shape), board_shape)
  File "/home/libra/anaconda3/envs/vq_vae/lib/python3.9/site-packages/trimesh/base.py", line 2939, in difference
    result = boolean.difference(meshes=np.append(self, other),
  File "/home/libra/anaconda3/envs/vq_vae/lib/python3.9/site-packages/trimesh/boolean.py", line 25, in difference
    result = _engines[engine](meshes, operation='difference', **kwargs)
  File "/home/libra/anaconda3/envs/vq_vae/lib/python3.9/site-packages/trimesh/boolean.py", line 89, in boolean_automatic
    raise ValueError('No backends available for boolean operations!')
ValueError: No backends available for boolean operations!

**Comment by zyjiao4728** [comment]
Trimesh doesn't implement boolean operations on mesh internally, it uses either Blender or OpensCAD.
You can install Blender:
`sudo apt install blender`.
